Add shopify api payments tests
rubygarage/shopapp-shopify-ios pull request #13
Opened 2018-04-13 14:26 UTC by AntonoffEvgeniy

2018-04-13 15:02 UTC, radyslavkrechet approved these changes

2018-04-13 15:02 UTC, radyslavkrechet approved these changes

2018-04-16 08:12 UTC, plzen requested changes
Please, resolve conflicts

2018-04-16 08:50 UTC, plzen approved these changes

2018-04-16 08:50 UTC, merged