Add customer api tests
rubygarage/shopapp-shopify-ios pull request #14
Opened 2018-04-16 12:36 UTC by radyslavkrechet

2018-04-16 12:54 UTC, AntonoffEvgeniy requested changes

2018-04-16 12:54 UTC, AntonoffEvgeniy commented on ShopifyTests/API/ShopifyAPI/ShopifyAPICustomerSpec.swift
> +            context("f key chain has correct data") {
'f' -> 'if'

2018-04-16 13:01 UTC, AntonoffEvgeniy approved these changes

2018-04-19 06:25 UTC, plzen approved these changes

2018-04-19 06:26 UTC, merged