Add shopify api pay method tests
rubygarage/shopapp-shopify-ios pull request #15
Opened 2018-04-17 12:06 UTC by AntonoffEvgeniy

2018-04-17 13:00 UTC, radyslavkrechet requested changes

2018-04-17 13:00 UTC, radyslavkrechet commented on Shopify/API/ShopifyAPI.swift
> +        cardClient = Card.Client.init()
Don't use `init`.

2018-04-17 13:08 UTC, radyslavkrechet approved these changes

2018-04-19 06:30 UTC, plzen requested changes
Looks good!!! Just fix conflicts and I'll merge it.

2018-04-19 09:42 UTC, plzen approved these changes

2018-04-19 09:43 UTC, merged